# Generated by Django 5.2.3 on 2025-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('faixa', models.CharField(choices=[('B', 'Branca'), ('C', 'Cinza'), ('L', 'Laranja'), ('A', 'Amarela'), ('V', 'Verde'), ('AZ', 'Azul'), ('R', 'Roxo'), ('M', 'Marrom'), ('P', 'Preta')], default='B', max_length=2)),
            ],
        ),
    ]
