# Generated by Django 5.2.3 on 2025-06-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulasConcluidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('faixa_atual', models.CharField(choices=[('B', 'Branca'), ('C', 'Cinza'), ('L', 'Laranja'), ('A', 'Amarela'), ('V', 'Verde'), ('AZ', 'Azul'), ('R', 'Roxo'), ('M', 'Marrom'), ('P', 'Preta')], default='B', max_length=2)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.alunos')),
            ],
        ),
    ]
